# # Use postgres/example user/password credentials
version: "3.1"
name: dicoding_belajar_fundamental_aplikasi_backend_notes_api
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: M@ntap23
      POSTGRES_USER: sarewes23
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080

volumes:
  local_postgres_data: {}
